### ISSUE TITLE
通知接口响应问题

### ISSUE THREAD

**Issue by 406965097** [gabinlin/wx-pay-profits-sharing#1]
老哥，支付完成之后的回调腾讯要求要返回xml格式响应信息吧？能在util里边或者在CombineTransactionsNotifyRequest1里边加一个静态方法吗？直接将结果解析为xml供响应腾讯的通知服务。给你一个map转xml的。
`public static String GetMapToXML(Map<String, String> param) {
        StringBuffer sb = new StringBuffer();
        sb.append("<xml>");
        for (Map.Entry<String, String> entry : param.entrySet()) {
            sb.append("<" + (String) entry.getKey() + ">");
            sb.append(entry.getValue());
            sb.append("</" + (String) entry.getKey() + ">");
        }
        sb.append("</xml>");
        return sb.toString();
    }`

**Comment by gabinlin** [comment]
你好，不是很明白什么意思哈。这边对接的是v3的版本，文档里面好像没有提及xml的回复，按文档来看，只要正常返回（http的应答码是200或204就是正常接收）
https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/pay/combine/chapter3_7.shtml <https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/pay/combine/chapter3_7.shtml>


> 2020年6月24日 下午3:49，406965097 <notifications@github.com> 写道：
> 
> CombineTransactionsNotifyRequest1

**Comment by 406965097** [comment]
哦，我文档看串了哈哈，不好意思

**Comment by ccf0411** [comment]
作者大大你好，能不能咨询个问题，使用您的工具包，成功获取到了prepayid，但是拼好参数用app调起微信去支付的时候遇到了问题，微信提示签名验证失败，但是使用微信给的验签工具验证是好着的，是不是SDK的问题呢，V3版接口支付app要使用的SDK和之前的不一样吗

**Comment by gabinlin** [comment]
> 作者大大你好，能不能咨询个问题，使用您的工具包，成功获取到了prepayid，但是拼好参数用app调起微信去支付的时候遇到了问题，微信提示签名验证失败，但是使用微信给的验签工具验证是好着的，是不是SDK的问题呢，V3版接口支付app要使用的SDK和之前的不一样吗

你好，我这边测试倒是没有用过app调试过支付。但js和app的确实是不同的。
理论上是调用：
Optional<String> combineTransactions(CombineTransactionsAppRequest request); // 获取prepayid，这个应该大同小异
Map<String, String> getAppPayParams(String prePayId, String appId); // 获取支付需要的参数和签名，这个和js的签名组装的顺序和参数值有点不一样，可以细看下源码

由于没有测试过app支付，不能保证是正常的，只是就我知道的app的签名是和js的不一样

**Comment by ccf0411** [comment]
好的，谢谢

> > 作者大大你好，能不能咨询个问题，使用您的工具包，成功获取到了prepayid，但是拼好参数用app调起微信去支付的时候遇到了问题，微信提示签名验证失败，但是使用微信给的验签工具验证是好着的，是不是SDK的问题呢，V3版接口支付app要使用的SDK和之前的不一样吗
> 
> 你好，我这边测试倒是没有用过app调试过支付。但js和app的确实是不同的。
> 理论上是调用：
> Optional combineTransactions(CombineTransactionsAppRequest request); // 获取prepayid，这个应该大同小异
> Map<String, String> getAppPayParams(String prePayId, String appId); // 获取支付需要的参数和签名，这个和js的签名组装的顺序和参数值有点不一样，可以细看下源码
> 
> 由于没有测试过app支付，不能保证是正常的，只是就我知道的app的签名是和js的不一样

好的，谢谢！
